// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPirate struct {
	Name     string `json:"name"`
	PirateID string `json:"pirateId"`
}

type Pirate struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
